### ISSUE TITLE
红米k20pro miui12  安卓10  edxposed(sandhook)报错

### ISSUE THREAD

**Issue by ghost** [ohyeah521/NoAds-For-YouTube#18]
java.lang.RuntimeException: Unable to instantiate application com.NoAdsBackgroundPlaybackYT.base.MyApplication: java.lang.ClassNotFoundException: Didn't find class "com.NoAdsBackgroundPlaybackYT.base.MyApplication" on path: DexPathList[[zip file "/data/app/com.NoAdsBackgroundPlaybackYT-w0uBgC6Kvl8ObzYHt0n6Rw==/base.apk"],nativeLibraryDirectories=[/data/app/com.NoAdsBackgroundPlaybackYT-w0uBgC6Kvl8ObzYHt0n6Rw==/lib/arm64, /system/lib64, /system/product/lib64]]
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1230)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6598)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:375)
	at SandHookerNew_5sm3dthec8858ee0to4kj3c1ge.hook(Unknown Source:51)
	at android.app.ActivityThread.access$1400(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7610)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.NoAdsBackgroundPlaybackYT.base.MyApplication" on path: DexPathList[[zip file "/data/app/com.NoAdsBackgroundPlaybackYT-w0uBgC6Kvl8ObzYHt0n6Rw==/base.apk"],nativeLibraryDirectories=[/data/app/com.NoAdsBackgroundPlaybackYT-w0uBgC6Kvl8ObzYHt0n6Rw==/lib/arm64, /system/lib64, /system/product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1156)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1222)
	... 13 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.NoAdsBackgroundPlaybackYT-w0uBgC6Kvl8ObzYHt0n6Rw==/base.apk because: Failure to verify dex file '/data/app/com.NoAdsBackgroundPlaybackYT-w0uBgC6Kvl8ObzYHt0n6Rw==/base.apk': out-of-order direct method indexes 4503 and 4500
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:369)
		at dalvik.system.DexFile.<init>(DexFile.java:107)
		at dalvik.system.DexFile.<init>(DexFile.java:80)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:457)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:403)
		at dalvik.system.DexPathList.<init>(DexPathList.java:164)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:126)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:101)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:74)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:87)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:116)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:114)
		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:60)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:853)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:952)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
		at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:375)
		at SandHookerNew_35f4vrpdo2vmlbkhbqk0r22p8o.hook(Unknown Source:46)
		at android.app.LoadedApk.getResources(LoadedApk.java:1190)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:2474)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:2466)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6483)
		... 12 more

**Comment by ohyeah521** [comment]
你看看你安装的软件开发者是谁，网上有个盗版的，请别安装错了
