### ISSUE TITLE
Crash on app start

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ohyeah521/NoAds-For-YouTube#24]
Redmi Note 2
Android 8.1
YouTube version: 15.37.35

Log:
```
09-26 00:36:19.147 I/Xposed  (  285): -----------------
09-26 00:36:19.147 I/Xposed  (  285): Starting Xposed version 90-beta3, compiled for SDK 27
09-26 00:36:19.147 I/Xposed  (  285): Device: Redmi Note 2 (Xiaomi), Android version 8.1.0 (SDK 27)
09-26 00:36:19.147 I/Xposed  (  285): ROM: lineage_hermes-userdebug 8.1.0 OPM7.181205.001 f2fb6e986c test-keys
09-26 00:36:19.147 I/Xposed  (  285): Build fingerprint: Xiaomi/hermes/hermes:5.0.2/LRX22G/V9.6.3.0.LHMMIFD:user/release-keys
09-26 00:36:19.147 I/Xposed  (  285): Platform: arm64-v8a, 64-bit binary, system server: yes
09-26 00:36:19.147 I/Xposed  (  285): SELinux enabled: yes, enforcing: no
09-26 00:36:22.688 I/Xposed  (  285): -----------------
09-26 00:36:22.688 I/Xposed  (  285): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-26 00:36:25.533 I/Xposed  (  285): Detected ART runtime
09-26 00:36:25.539 I/Xposed  (  285): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-26 00:36:26.088 I/Xposed  (  285): Loading modules from /data/app/com.NoAdsBackgroundPlaybackYT-pRv4R_rTTrx6pL2tzNmrtw==/base.apk
09-26 00:36:26.350 E/Xposed  (  285):   Cannot load module
09-26 00:36:26.350 E/Xposed  (  285): java.io.IOException: Failed to open dex files from /data/app/com.NoAdsBackgroundPlaybackYT-pRv4R_rTTrx6pL2tzNmrtw==/base.apk because: Failure to verify dex file '/data/app/com.NoAdsBackgroundPlaybackYT-pRv4R_rTTrx6pL2tzNmrtw==/base.apk': out-of-order direct method indexes 4503 and 4500
09-26 00:36:26.350 E/Xposed  (  285): 	at dalvik.system.DexFile.openDexFileNative(Native Method)
09-26 00:36:26.350 E/Xposed  (  285): 	at dalvik.system.DexFile.openDexFile(DexFile.java:353)
09-26 00:36:26.350 E/Xposed  (  285): 	at dalvik.system.DexFile.<init>(DexFile.java:100)
09-26 00:36:26.350 E/Xposed  (  285): 	at dalvik.system.DexFile.<init>(DexFile.java:86)
09-26 00:36:26.350 E/Xposed  (  285): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:485)
09-26 00:36:26.350 E/Xposed  (  285): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:466)
09-26 00:36:26.350 E/Xposed  (  285): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:97)
09-26 00:36:29.276 I/Xposed  (  286): -----------------
09-26 00:36:29.276 I/Xposed  (  286): Starting Xposed version 90-beta3, compiled for SDK 27
09-26 00:36:29.276 I/Xposed  (  286): Device: Redmi Note 2 (Xiaomi), Android version 8.1.0 (SDK 27)
09-26 00:36:29.276 I/Xposed  (  286): ROM: lineage_hermes-userdebug 8.1.0 OPM7.181205.001 f2fb6e986c test-keys
09-26 00:36:29.276 I/Xposed  (  286): Build fingerprint: Xiaomi/hermes/hermes:5.0.2/LRX22G/V9.6.3.0.LHMMIFD:user/release-keys
09-26 00:36:29.276 I/Xposed  (  286): Platform: arm64-v8a, 32-bit binary, system server: no
09-26 00:36:29.276 I/Xposed  (  286): SELinux enabled: yes, enforcing: no
09-26 00:36:31.948 I/Xposed  (  286): -----------------
09-26 00:36:31.948 I/Xposed  (  286): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-26 00:36:33.437 I/Xposed  (  286): Detected ART runtime
09-26 00:36:33.444 I/Xposed  (  286): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-26 00:36:33.826 I/Xposed  (  286): Loading modules from /data/app/com.NoAdsBackgroundPlaybackYT-pRv4R_rTTrx6pL2tzNmrtw==/base.apk
09-26 00:36:33.993 E/Xposed  (  286):   Cannot load module
09-26 00:36:33.993 E/Xposed  (  286): java.io.IOException: Failed to open dex files from /data/app/com.NoAdsBackgroundPlaybackYT-pRv4R_rTTrx6pL2tzNmrtw==/base.apk because: Failure to verify dex file '/data/app/com.NoAdsBackgroundPlaybackYT-pRv4R_rTTrx6pL2tzNmrtw==/base.apk': out-of-order direct method indexes 4503 and 4500
09-26 00:36:33.993 E/Xposed  (  286): 	at dalvik.system.DexFile.openDexFileNative(Native Method)
09-26 00:36:33.993 E/Xposed  (  286): 	at dalvik.system.DexFile.openDexFile(DexFile.java:353)
09-26 00:36:33.993 E/Xposed  (  286): 	at dalvik.system.DexFile.<init>(DexFile.java:100)
09-26 00:36:33.993 E/Xposed  (  286): 	at dalvik.system.DexFile.<init>(DexFile.java:86)
09-26 00:36:33.993 E/Xposed  (  286): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:485)
09-26 00:36:33.993 E/Xposed  (  286): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:466)
09-26 00:36:33.993 E/Xposed  (  286): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:97)
09-26 00:36:37.112 W/Xposed  (  634): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@LineageSettingsProvider@LineageSettingsProvider.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@LineageSettingsProvider@LineageSettingsProvider.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:37.427 W/Xposed  (  634): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@LineageParts@LineageParts.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@LineageParts@LineageParts.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:40.543 W/Xposed  (  793): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@LatinIME@LatinIME.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@LatinIME@LatinIME.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:40.556 W/Xposed  (  807): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@SystemUI@SystemUI.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@SystemUI@SystemUI.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:41.336 W/Xposed  (  936): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@TeleService@TeleService.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@TeleService@TeleService.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:41.401 W/Xposed  (  962): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@Settings@Settings.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@Settings@Settings.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:41.479 W/Xposed  (  936): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@TelephonyProvider@TelephonyProvider.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@TelephonyProvider@TelephonyProvider.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:50.030 W/Xposed  ( 1276): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@DeskClock@DeskClock.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@DeskClock@DeskClock.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:50.415 W/Xposed  ( 1358): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@Trebuchet@Trebuchet.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@Trebuchet@Trebuchet.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:50.461 W/Xposed  ( 1325): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@AudioFX@AudioFX.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@AudioFX@AudioFX.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:50.591 W/Xposed  ( 1373): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@WAPPushManager@WAPPushManager.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@WAPPushManager@WAPPushManager.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:50.771 W/Xposed  ( 1416): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@PrintSpooler@PrintSpooler.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@PrintSpooler@PrintSpooler.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:51.657 W/Xposed  ( 1489): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@DownloadProvider@DownloadProvider.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@DownloadProvider@DownloadProvider.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:51.697 W/Xposed  ( 1489): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@MediaProvider@MediaProvider.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@MediaProvider@MediaProvider.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:56.825 W/Xposed  ( 1968): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@LineageParts@LineageParts.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@LineageParts@LineageParts.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:57.984 W/Xposed  ( 2063): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@Dialer@Dialer.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@Dialer@Dialer.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:58.350 W/Xposed  ( 2081): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@CarrierConfig@CarrierConfig.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@CarrierConfig@CarrierConfig.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:58.627 W/Xposed  ( 2116): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@ContactsProvider@ContactsProvider.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@ContactsProvider@ContactsProvider.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:58.823 W/Xposed  ( 2116): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@BlockedNumberProvider@BlockedNumberProvider.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@BlockedNumberProvider@BlockedNumberProvider.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:58.853 W/Xposed  ( 2116): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@UserDictionaryProvider@UserDictionaryProvider.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@UserDictionaryProvider@UserDictionaryProvider.apk@classes.dex@xposed' : No such file or directory
09-26 00:36:59.971 W/Xposed  ( 2148): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@webview@webview.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@webview@webview.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:00.255 W/Xposed  (  876): Failed to load Xposed info for /data/dalvik-cache/arm/system@app@webview@webview.apk@classes.dex: Unable to open '/data/dalvik-cache/arm/data@dalvik-cache@arm@system@app@webview@webview.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:02.314 W/Xposed  ( 2380): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@Calendar@Calendar.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@Calendar@Calendar.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:02.691 W/Xposed  ( 2432): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@CellBroadcastReceiver@CellBroadcastReceiver.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@CellBroadcastReceiver@CellBroadcastReceiver.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:02.746 W/Xposed  ( 2449): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@CalendarProvider@CalendarProvider.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@CalendarProvider@CalendarProvider.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:02.904 W/Xposed  ( 2475): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@Contacts@Contacts.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@Contacts@Contacts.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:03.243 W/Xposed  ( 2505): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@Email@Email.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@Email@Email.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:03.384 W/Xposed  ( 2524): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@Exchange2@Exchange2.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@Exchange2@Exchange2.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:03.523 W/Xposed  ( 2548): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@ManagedProvisioning@ManagedProvisioning.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@ManagedProvisioning@ManagedProvisioning.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:03.672 W/Xposed  ( 2570): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@messaging@messaging.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@messaging@messaging.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:03.973 W/Xposed  ( 2595): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@OneTimeInitializer@OneTimeInitializer.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@OneTimeInitializer@OneTimeInitializer.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:03.998 W/Xposed  (  936): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@MmsService@MmsService.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@MmsService@MmsService.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:04.196 W/Xposed  (  936): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@Stk@Stk.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@Stk@Stk.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:06.993 W/Xposed  ( 2869): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@LineageParts@LineageParts.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@LineageParts@LineageParts.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:07.163 W/Xposed  ( 2889): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@LockClock@LockClock.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@LockClock@LockClock.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:07.255 W/Xposed  ( 2906): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@Updater@Updater.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@Updater@Updater.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:09.862 W/Xposed  ( 3058): Failed to load Xposed info for /data/dalvik-cache/arm64/system@priv-app@CarrierConfig@CarrierConfig.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@priv-app@CarrierConfig@CarrierConfig.apk@classes.dex@xposed' : No such file or directory
09-26 00:37:09.982 W/Xposed  ( 3075): Failed to load Xposed info for /data/dalvik-cache/arm64/system@app@CarrierDefaultApp@CarrierDefaultApp.apk@classes.dex: Unable to open '/data/dalvik-cache/arm64/data@dalvik-cache@arm64@system@app@CarrierDefaultApp@CarrierDefaultApp.apk@classes.dex@xposed' : No such file or directory
```

**Comment by ohyeah521** [comment]
download from https://repo.xposed.info/module/wovow.youtubehelper, maybe you had download a fake

**Comment by vitaly-zdanevich** [comment]
Thank you, now it works, can you please remove this broken version?
![Screenshot_20200928-214054_Xposed_Installer](https://user-images.githubusercontent.com/3514015/94472889-16137300-01d4-11eb-8d43-49f3ef7338dd.png)

**Comment by ohyeah521** [comment]
> Thank you, now it works, can you please remove this broken version?
 this is a fake version,no upload by me,so i can not do this,

**Comment by vitaly-zdanevich** [comment]
Maybe you can write to the administration of this listing?
